#!/bin/sh
#	$Id$
#	maketoc file...
#
for f in $*; do
  if [ -f $f.bak ]; then
     if [ -f $f.orig ]; then
        rm $f.bak
     else 
        mv $f.bak $f.orig
     fi
  fi
  mv $f $f.bak
  process -t toc $f.bak > $f
done
